apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRE5yWEhaQmNHT0V3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBek1USXhOekF6TVRWYUZ3MHpOakF6TURreE56QTRNVFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUR3emhqYTZ4dWN2SE1ZaEpJTEhlMnBXaFRWM0dNbXdJaElEYkNhWDNpa01HUC9JdEpYU2FQMlR6amcKTDBLUGlTL04yeFJRSkUxcnR3UkVPUEsxWk1SU3hzSStLbWcraHZqK0Y3TDNSWGM3QXdENmRXN21DakZXVWRSegovaVBQcms2dS9PRTFWRnk0RzVEQXQwdHBKb1k4Rmk4WGVGdWl2MkN2ZjI4M2hHY01VTGIydTBmUE9Md2t4R3FiCm5DRjBEZ0dldit0NWU1ZW4rRTh1RDFZbWIwbzZxMVUrV2FTaXZQb2RMRWF2Nldmb2dhcGxwQUF1UzZ5LzErZUcKVSs4N3FabU5qemFxWFpDelZKRzR4NjRXbWpVTTk5aTRRN1loSWZ4Vk52RWtodjZmUk9mQitFTk9mMWdwR3d0LwpYM1ZiWEFmdkF1QWlFV0Q5dFJ0NllmU21YS0FCQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTYWsxeEhJNWdlU1VQWXkvRXRMM0ppNWltK2tqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRREtvY3JWd1NZMgphVzJ2NHJyTXRWazRqdHZBR3BqYTVJVUNMZVdlNjNYMkdiQVFueEJNVUtvN2JEWUdUaDhQSXpkOGxOcDZ3M09iCjZvZmRxTlNKNVJoMFEyeEhWTDlLNnNWRHJZV0o3aERWSDhSTmQ3THpMdEtCakNLVHlpdkJLcXg1blZvR084dFoKY2FjOWRRRituZWdmbjNFSVcrWldNN1JqZ016RDVNME5vcHhRSm9aNWJET3lkQXJZU1Ixd2Q2VEdQblJhUXgxMQpQOGw0WkUwQzhnVkkvaW9oNUtpY1lENWlYN2Vqd0lZNGZ0Y1RXSlQ3dElSR0xiTlhJUktvdDBYN1ZQaTRWU0tUCnIwSXFXZURJaiszQk5KSGdFM0ZKNk5xYlloUDl4TGxBTER6UzRZRE81ZW03aUtKQ1B2bGZYTmRGYUdrOFNmUFoKSnpnZGtPeGlxMWhwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://8D0564791FE781B22BD8BEF98606C77C.yl4.ap-south-1.eks.amazonaws.com
  name: arn:aws:eks:ap-south-1:665602132627:cluster/P2AD-eks
contexts:
- context:
    cluster: arn:aws:eks:ap-south-1:665602132627:cluster/P2AD-eks
    user: arn:aws:eks:ap-south-1:665602132627:cluster/P2AD-eks
  name: arn:aws:eks:ap-south-1:665602132627:cluster/P2AD-eks
current-context: arn:aws:eks:ap-south-1:665602132627:cluster/P2AD-eks
kind: Config
preferences: {}
users:
- name: arn:aws:eks:ap-south-1:665602132627:cluster/P2AD-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-south-1
      - eks
      - get-token
      - --cluster-name
      - P2AD-eks
      - --output
      - json
      command: aws
